language: python

python:
- "2.7"
- "3.6"

dist: trusty
#sudo: required
sudo: false

addons:
  apt:
    packages:
      - libarmadillo-dev
      - g++
      - gfortran
      - liblapack-dev
      - libopenblas-dev
before_install:
  - pip install git+https://github.com/doconce/preprocess#egg=preprocess
  - pip install git+https://github.com/doconce/doconce#egg=doconce

script:
  - doconce --version
  - cd doc/src/ && time bash make.sh && cd -
